#!/usr/bin/env bash

set -e

sudo apt-get install -y --no-install-recommends --allow-downgrades \
    ca-certificates \
    git \
    zsh \
    exa \
    jq \
    wget \
    curl \
    vim \
    zsh-theme-powerlevel9k

curl -sfL git.io/antibody | sodu sh -s - -b /usr/local/bin

CONFIG="install.conf.yaml"
SUDO_CONFIG="install-sudo.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
