#!/usr/bin/env bash

set -e

####################
# Install packages #
####################

sudo apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
      ca-certificates \
      git \
      zsh \
      exa \
      jq \
      wget \
      curl \
      vim \
      zsh-theme-powerlevel9k

sudo curl -sfL git.io/antibody | sh -s - -b /usr/local/bin

###########
# Dot Bot #
###########

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
