#!/bin/bash

echo "               _   _       __        __   __ "
echo "    ____ ___  (_)_(_)___  _\_\ _____/ /__/_/ "
echo "   / __ `__ \/ __ `/_  / / _ \/ ___/ __/ _ \ "
echo "  / / / / / / /_/ / / /_/  __/ /  / /_/  __/ "
echo " /_/ /_/ /_/\__,_/ /___/\___/_/   \__/\___/  "


start() {
    clear
    curl ip.gs
    echo ""
    echo "============================================="
    echo "               _   _       __        __   __ "
    echo "    ____ ___  (_)_(_)___  _\_\ _____/ /__/_/ "
    echo "   / __ `__ \/ __ `/_  / / _ \/ ___/ __/ _ \ "
    echo "  / / / / / / /_/ / / /_/  __/ /  / /_/  __/ "
    echo " /_/ /_/ /_/\__,_/ /___/\___/_/   \__/\___/  "
    echo "                                             "
    echo "============================================="
    echo "              !! ATTENTION !!"
    echo "YOU ARE SETTING UP: mäzèrté Environment"
    echo "============================================="

    cd $HOME
}

install-linux-packages() {
    echo "==========================================================="
    echo "* Install following packages:"
    echo "-----------------------------------------------------------"

    sudo apt-get update
    sudo apt-get install -y apt-file aptitude deborphan
    sudo apt-get install -y build-essential libreadline-dev
    sudo apt-get install -y zsh curl wget git tree unzip ncdu tmux trash-cli
    sudo apt-get install -y lsof whois traceroute
    sudo apt-get install -y net-tools iputils-tracepath dnsutils
    sudo apt-get install -y netcat-openbsd
    sudo apt-get install -y exa jq vim
    sudo apt-get install -y zsh-theme-powerlevel9k
}

install-antibody(){
    curl -sfL git.io/antibody | sudo sh -s - -b /usr/local/bin
}

run-dotbot() {
    echo "==========================================================="
    echo "                  Run DotBot                   "
    echo "-----------------------------------------------------------"

    CONFIG="install.conf.yaml"
    DOTBOT_DIR="dotbot"

    DOTBOT_BIN="bin/dotbot"
    BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    cd "${BASEDIR}"
    git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
    git submodule update --init --recursive "${DOTBOT_DIR}"

    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
}

upgrade-packages() {
    echo "==========================================================="
    echo "                      Upgrade packages                     "
    echo "-----------------------------------------------------------"

    sudo apt-get update && sudo apt-get upgrade -y
}

finish() {
    echo "==========================================================="
    echo "> Do not forget run those things:"
    echo ""
    echo "- chsh -s /usr/bin/zsh"
    echo "- git-config"
    echo "- set up neovim"
    echo "- u-update"
    echo "==========================================================="
}

start
install-linux-packages
install-antibody
run-dotbot
upgrade-packages
finish
